services:
    oro_behat.extension.isolation.database:
        class: 'Oro\BehatExtension\DatabaseBehatExtension\Legacy\OroDatabaseBehatIsolator'
        lazy: true
        arguments:
            - '@oro_db_extension.engine.registry'
            - '~'
        tags:
            - { name: 'oro_behat.isolator', priority: 110 }
            - { name: 'event_dispatcher.subscriber', priority: 0 }
